<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Order;
use Illuminate\Http\Request;

class AdminOrderController extends Controller
{
    public function index(Request $request)
    {
        $query = Order::with(['user', 'items.product', 'couponCode', 'deliveryBoy']);

        // Handle section-based filtering
        if ($request->has('section')) {
            $section = $request->section;
            switch ($section) {
                case 'pending':
                    $query->where('status', 'pending');
                    break;
                case 'ready-for-shipping':
                    // Orders that are processing (ready to be shipped)
                    $query->where('status', 'processing');
                    break;
                case 'shipped':
                    $query->where('status', 'shipped');
                    break;
                case 'out-for-delivery':
                    $query->where('status', 'out_for_delivery');
                    break;
                case 'delivered':
                    $query->where('status', 'delivered');
                    break;
                case 'failed-delivery':
                    $query->where('status', 'cancelled');
                    break;
                case 'picked-up':
                    // Map to completed for now
                    $query->where('status', 'completed');
                    break;
                case 'completed':
                    $query->where('status', 'completed');
                    break;
                case 'cancelled':
                    $query->where('status', 'cancelled');
                    break;
                case 'return-refund':
                $query->where('return_status', 'pending')
                    ->orWhere('return_status', 'approved')
                    ->orWhere('return_status', 'refunded')
                    ->orWhere('status', 'return_refund');
                    break;
                case 'processed':
                    // Orders that are shipped or completed
                    $query->whereIn('status', ['shipped', 'completed']);
                    break;
                case 'all':
                    // No status filter - show all orders
                    break;
                default:
                    // If no section or invalid section, show all
                    break;
            }
        } elseif ($request->has('status')) {
            // Legacy support for direct status filtering
            $query->where('status', $request->status);
        }

        if ($request->has('search')) {
            $query->where(function($q) use ($request) {
                $q->where('id', 'like', '%' . $request->search . '%')
                  ->orWhere('order_number', 'like', '%' . $request->search . '%')
                  ->orWhere('email', 'like', '%' . $request->search . '%')
                  ->orWhere('name', 'like', '%' . $request->search . '%')
                  ->orWhereHas('user', function($userQuery) use ($request) {
                      $userQuery->where('name', 'like', '%' . $request->search . '%')
                                ->orWhere('email', 'like', '%' . $request->search . '%');
                  });
            });
        }

        // Date range filter
        if ($request->has('start_date') && $request->has('end_date')) {
            $query->whereBetween('created_at', [
                \Carbon\Carbon::parse($request->start_date)->startOfDay(),
                \Carbon\Carbon::parse($request->end_date)->endOfDay()
            ]);
        }

        $orders = $query->latest()->paginate(15);

        return $this->sendJsonResponse(true, 'Orders fetched successfully', $orders, 200);
    }

    public function show(Request $request)
    {
        $request->validate([
            'id' => 'required|exists:orders,id',
        ]);

        $order = Order::with(['user', 'items.product', 'couponCode', 'deliveryBoy'])->findOrFail($request->id);

        return $this->sendJsonResponse(true, 'Order fetched successfully', $order, 200);
    }

    public function updateStatus(Request $request)
    {
        $request->validate([
            'id' => 'required|exists:orders,id',
            'status' => 'required|in:pending,processing,shipped,completed,cancelled,ready_for_shipping,out_for_delivery,delivered,failed_delivery,picked_up,return_refund,returned',
        ]);

        $order = Order::findOrFail($request->id);
        
        // Map UI statuses to database statuses
        $statusMapping = [
            'ready_for_shipping' => 'processing',
            'out_for_delivery' => 'out_for_delivery',
            'delivered' => 'delivered',
            'failed_delivery' => 'cancelled',
            'picked_up' => 'completed',
            'return_refund' => 'return_refund',
        ];
        
        $status = $statusMapping[$request->status] ?? $request->status;
        
        // OTP will be generated by delivery boy from their dashboard
        $order->update(['status' => $status]);

        return $this->sendJsonResponse(true, 'Order status updated successfully', $order->fresh(), 200);
    }

    public function cancel(Request $request)
    {
        $request->validate([
            'id' => 'required|exists:orders,id',
            'cancellation_reason' => 'nullable|string|in:customer_request,out_of_stock,payment_failed,delivery_issue,changed_mind,found_better_price,wrong_item,delivery_address_incorrect,delayed_delivery,other',
            'cancellation_notes' => 'nullable|string|max:500',
        ]);

        $order = Order::findOrFail($request->id);

        if ($order->status === 'cancelled') {
            return $this->sendJsonResponse(false, 'Order is already cancelled', [], 400);
        }

        if ($order->status === 'completed') {
            return $this->sendJsonResponse(false, 'Cannot cancel completed order', [], 400);
        }

        $order->update([
            'status' => 'cancelled',
            'cancellation_reason' => $request->cancellation_reason,
            'cancellation_notes' => $request->cancellation_notes,
        ]);

        return $this->sendJsonResponse(true, 'Order cancelled successfully', $order->fresh(), 200);
    }

    public function approveReturn(Request $request)
    {
        $request->validate([
            'id' => 'required|exists:orders,id',
        ]);

        $order = Order::findOrFail($request->id);

        if ($order->return_status !== 'pending') {
            return $this->sendJsonResponse(false, 'Return request is not pending', [], 400);
        }

        // Calculate refund amount (full order total)
        $refundAmount = $order->total;

        $order->update([
            'return_status' => 'approved',
            'refund_amount' => $refundAmount,
            'return_processed_at' => now(),
            'status' => 'return_refund',
        ]);

        return $this->sendJsonResponse(true, 'Return approved and refund processed successfully', $order->fresh(), 200);
    }

    public function rejectReturn(Request $request)
    {
        $request->validate([
            'id' => 'required|exists:orders,id',
            'rejection_reason' => 'nullable|string|max:500',
        ]);

        $order = Order::findOrFail($request->id);

        if ($order->return_status !== 'pending') {
            return $this->sendJsonResponse(false, 'Return request is not pending', [], 400);
        }

        $order->update([
            'return_status' => 'rejected',
            'return_notes' => $request->rejection_reason ? ($order->return_notes . ' | Rejection: ' . $request->rejection_reason) : $order->return_notes,
            'return_processed_at' => now(),
        ]);

        return $this->sendJsonResponse(true, 'Return request rejected', $order->fresh(), 200);
    }

    public function processRefund(Request $request)
    {
        $request->validate([
            'id' => 'required|exists:orders,id',
        ]);

        $order = Order::findOrFail($request->id);

        if ($order->return_status !== 'approved') {
            return $this->sendJsonResponse(false, 'Return must be approved before processing refund', [], 400);
        }

        if ($order->return_status === 'refunded') {
            return $this->sendJsonResponse(false, 'Refund already processed', [], 400);
        }

        $order->update([
            'return_status' => 'refunded',
            'return_processed_at' => now(),
        ]);

        return $this->sendJsonResponse(true, 'Refund processed successfully', $order->fresh(), 200);
    }

    public function updateDeliveryDate(Request $request)
    {
        $request->validate([
            'id' => 'required|exists:orders,id',
            'delivery_date' => 'required|date|after_or_equal:today',
        ]);

        $order = Order::findOrFail($request->id);

        $order->update([
            'delivery_date' => $request->delivery_date,
        ]);

        return $this->sendJsonResponse(true, 'Delivery date updated successfully', $order->fresh(), 200);
    }

    public function getCounts(Request $request)
    {
        $counts = [
            'all' => Order::count(),
            'pending' => Order::where('status', 'pending')->count(),
            'ready-for-shipping' => Order::where('status', 'processing')->count(),
            'shipped' => Order::where('status', 'shipped')->count(),
            'out-for-delivery' => Order::where('status', 'out_for_delivery')->count(),
            'delivered' => Order::where('status', 'delivered')->count(),
            'failed-delivery' => Order::where('status', 'cancelled')->count(),
            'picked-up' => Order::where('status', 'completed')->count(),
            'completed' => Order::where('status', 'completed')->count(),
            'cancelled' => Order::where('status', 'cancelled')->count(),
            'return-refund' => Order::where(function($query) {
                $query->where('return_status', 'pending')
                    ->orWhere('return_status', 'approved')
                    ->orWhere('return_status', 'refunded')
                    ->orWhere('status', 'return_refund');
            })->count(),
            'processed' => Order::whereIn('status', ['shipped', 'completed'])->count(),
        ];

        return $this->sendJsonResponse(true, 'Order counts fetched successfully', $counts, 200);
    }

    public function assignDeliveryBoy(Request $request)
    {
        $request->validate([
            'id' => 'required|exists:orders,id',
            'delivery_boy_id' => 'required|exists:users,id',
        ]);

        $order = Order::findOrFail($request->id);
        $deliveryBoy = \App\Models\User::findOrFail($request->delivery_boy_id);

        // Check if user is a delivery boy
        if ($deliveryBoy->role !== 'delivery_boy') {
            return $this->sendJsonResponse(false, 'Selected user is not a delivery boy', [], 400);
        }

        // Assign delivery boy (OTP will be generated by delivery boy from their dashboard)
        $order->update([
            'delivery_boy_id' => $request->delivery_boy_id,
            'status' => 'out_for_delivery',
        ]);

        return $this->sendJsonResponse(true, 'Delivery boy assigned successfully. Delivery boy can generate OTP from their dashboard.', $order->fresh(['deliveryBoy']), 200);
    }

    public function getDeliveryBoys(Request $request)
    {
        $deliveryBoys = \App\Models\User::where('role', 'delivery_boy')
            ->select('id', 'name', 'email', 'phone')
            ->get();

        return $this->sendJsonResponse(true, 'Delivery boys fetched successfully', $deliveryBoys, 200);
    }
}

